

all:
	java -jar ../_soy/SoyToJsSrcCompiler.jar --outputPathFormat generated/en.js --srcs ../common.soy,template.soy,../code/template.soy,../graph/template.soy,../maze/template.soy,../plane/template.soy,../puzzle/template.soy,../turtle/template.soy
